spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google: # https://console.cloud.google.com/
            client-id: GOOGLE_CLIENT_ID
            client-secret: GOOGLE_CLIENT_SECRET
          facebook: # https://developers.facebook.com/apps
            client-id: FACEBOOK_CLIENT_ID
            client-secret: FACEBOOK_CLIENT_SECRET
  main:
    allow-circular-references: true

custom:
  oauth2:
    kakao: # https://developers.kakao.com/
      client-id: kakao_REST_API_KEY

logging:
  level:
    root: DEBUG
server:
  port: 8080
